### ISSUE TITLE
DESCRIPCIÓN DEL JUEGO

### ISSUE THREAD

**Issue by PabloClaramonte** [PabloClaramonte/VOXHEAD#1]
El juego consistirá en un arcade de varios niveles cuyo objetivo será destruir tantos ladrillos como nos requiera el nivel en el que estemos. Para ello, haremos rebotar una bola sobre una plataforma móvil a lo largo del eje x. 

Este juego se basará en el clásico de Blackberry "Brick Breaker".

**Comment by amsamuel5498** [comment]
Vamos vamos que nos vamos

**Comment by ghost** [comment]
Cashate samsagaz
